export const LOADING_GET_LANG = 'get-lang'
export const LOADING_GET_OPTIONS = 'get-options'
export const LOADING_GET_CURRENCY = 'get-currency'
export const LOADING_CREATE_CURRENCY = 'get-currency'
export const LOADING_DELETE_CURRENCY = 'get-currency'
